version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-sistema-aprendizagem
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  api:
    build: .
    container_name: api-sistema-aprendizagem
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/sistema-aprendizagem?authSource=admin
      SESSION_SECRET: your-super-secret-session-key-change-this-in-production
      NODE_ENV: development
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge